### ISSUE TITLE
Use the `mold` linker instead of `ld` or `lld`

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#547]
[`mold`](https://github.com/rui314/mold) is a faster linker that benefits from parallelization. It should be easy enough to use as a drop-in replacement, there are even Rust-specific instructions:

If using Rust, create a `.cargo/config.toml` in your project directory with the following:
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/path/to/mold"]
```

Other relevant details here: https://stackoverflow.com/questions/67511990/how-to-use-the-mold-linker-with-cargo
